// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGklXmNP-TsR-uI8J9Ru7zvrcJJtNKsMA',
    appId: '1:4204670045:web:6019b0308bce317f2eb1b4',
    messagingSenderId: '4204670045',
    projectId: 'fir-projetcs-f3acc',
    authDomain: 'fir-projetcs-f3acc.firebaseapp.com',
    storageBucket: 'fir-projetcs-f3acc.appspot.com',
    measurementId: 'G-3WQ0THV10H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX26mvJC1a994GmA5uPp7oHVusuXsBB3Y',
    appId: '1:4204670045:android:625e2e51b025bdc42eb1b4',
    messagingSenderId: '4204670045',
    projectId: 'fir-projetcs-f3acc',
    storageBucket: 'fir-projetcs-f3acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb_OTKUyxGO-CJQt3vKXVlo3yzFwx79XE',
    appId: '1:4204670045:ios:7f27da685338d42e2eb1b4',
    messagingSenderId: '4204670045',
    projectId: 'fir-projetcs-f3acc',
    storageBucket: 'fir-projetcs-f3acc.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb_OTKUyxGO-CJQt3vKXVlo3yzFwx79XE',
    appId: '1:4204670045:ios:7f27da685338d42e2eb1b4',
    messagingSenderId: '4204670045',
    projectId: 'fir-projetcs-f3acc',
    storageBucket: 'fir-projetcs-f3acc.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGklXmNP-TsR-uI8J9Ru7zvrcJJtNKsMA',
    appId: '1:4204670045:web:a9566b69da5999d32eb1b4',
    messagingSenderId: '4204670045',
    projectId: 'fir-projetcs-f3acc',
    authDomain: 'fir-projetcs-f3acc.firebaseapp.com',
    storageBucket: 'fir-projetcs-f3acc.appspot.com',
    measurementId: 'G-8DH4GF9VPZ',
  );
}
